### ISSUE TITLE
Webpack outputting invalid javascript?

### ISSUE THREAD

**Issue by joshukraine** [craigmdennis/middleman-gulp-starter#8] opened 2016-04-06 12:51 UTC
Hey Craig, Thanks for all your work on this project. I'm learning a lot with it!

I've run into an issue which I think is related to webpack. I'm trying to add some javascript that uses jQuery. Everything works great in development, but when I run `middleman build`, the minified js file that gets put out has at least two syntax errors which prevent the browser from reading it.

By default, jQuery includes two blocks of comments (copyright stuff) and for some reason, the opening comment characters (`/*`) get attached to the end of the previous line of code. This means that the first commented line begins with just `*` and this causes an error.

I have a fork of your project which uses jQuery to illustrate. https://github.com/joshukraine/middleman-gulp-starter

You can see the minified `all.js` file in this gist: https://gist.github.com/joshukraine/5cfe351b3e22d8870f6d384795aa68bd Notice lines 2 and 15 and you'll see what I mean about the comments.

Any thoughts on why this might be happening and/or how to fix it? Thanks!

**Comment by craigmdennis** [comment] 2016-04-06 13:53
I'll take a look. I'm running this on a separate project that also has jQuery and works fine.

**Comment by craigmdennis** [comment] 2016-04-06 14:14
@joshukraine I've cloned your repo and am not getting any errors when running `middleman serve` or `middleman build`

What you've described shouldn't cause an error. What is the error you're experiencing? What's the output from the console?

**Comment by joshukraine** [comment] 2016-04-06 14:31
@craigmdennis Sorry, I may not have been clear. The site builds locally without any trouble. But once deployed, the browser seems to choke on the minified javascript file, and none of the javascript works. The error in the browser dev console is `Uncaught SyntaxError: Unexpected token *`. See the screenshot below for an example.

https://www.dropbox.com/s/ozheca2stp5pxuy/Screenshot%202016-04-06%2017.26.28.png?dl=0

The screenshot is from a live site I just finished upgrading to MM4. I ran into this issue after I deployed it this morning. The URL for the site is www.cmoproject.org and the repo for it is https://github.com/joshukraine/cmoproject.org.

**Comment by craigmdennis** [comment] 2016-04-06 14:43
I'm not getting any errors at all when I just put it up on S3 http://joshukraine-test.s3-website-eu-west-1.amazonaws.com/

**Comment by joshukraine** [comment] 2016-04-06 14:53
Hmm, that's odd. On cmoproject.org it definitely seems to be choking on line 15. Only difference I can see is that on that site I'm using Middleman asset hashing in the config.rb. Hence the filename "all-f100698d.js" as opposed to simply "all.js". I don't see why that would make a difference though.

Well, I suppose I'll keep digging. If you think of any suggestions, I'd appreciate it. Thanks for checking on this!

**Comment by craigmdennis** [comment] 2016-04-06 15:35
Ok there seems to be a bug with the Webpack uglify plugin preserving comments: https://github.com/webpack/webpack/issues/324

In the file `/gulpfile.js/lib/webpack-multi-config.js`

Replace: `new webpack.optimize.UglifyJsPlugin(),` with `new webpack.optimize.UglifyJsPlugin({ output: {comments: false} }),`

That seems to remove the comments for me

**Comment by joshukraine** [comment] 2016-04-06 15:55
OK, interesting. Well that _did_ work to remove all comments, but I've been digging some more over here and I think you were right initially in that the comments aren't actually the issue. I've got eslint going, and even when I fix the comments manually, I'm still getting the "Unexpected token error". After implementing the Uglify config you provided, the comments disappeared, but I'm still getting an error from eslint. For what it's worth, the js file from that test site you put up on AWS lints just fine. 

All my individual javascript files appear to be correct syntactically. (eslint doesn't complain) And when I run the local dev server there are no errors in the console. Somewhere in the build/bundle process something is getting tweaked. Anyway, I'll be sure to post back once I find it!

**Comment by craigmdennis** [comment] 2016-04-06 16:00
Ok. Well I'm going to close this issue with the above fix I suggested. Reopen if you find more info but I don't think it's directly related.

**Comment by joshukraine** [comment] 2016-04-06 16:01
Sounds good. Thanks again for your help.

**Closed as completed** 2016-04-06 16:23 UTC

**Comment by joshukraine** [comment] 2016-04-06 19:15
Found the problem. The syntax errors in the bundled javascript files were being cause by the `activate :asset_host` setting in config.rb. This is a setting [specifically recommended](https://middlemanapp.com/basics/build_and_deploy) in the Middleman docs, but if you activate it, the double slashes in the URL cause invalid javascript.

Check out this screenshot: https://www.dropbox.com/s/nmj5lmnpefwfcg4/Screenshot%202016-04-06%2021.17.00.png?dl=0

When I [removed the asset host config](https://github.com/joshukraine/cmoproject.org/commit/5ad0af2eb8e5faf44746d9fb638e3f96948e9995), the javascript builds and runs just fine. Only problem now is that I'm not using my CDN to serve my assets. :/

So do you think this is more a Middleman issue or something particular to combining webpack and Middleman?

**Comment by craigmdennis** [comment] 2016-04-06 20:31
Hmm... well the `//` simply means the it's protocol agnostic. So you don't have to specify `http://` or `https://`. It looks like the URL in the javascript isn't wrapped in `''` so it's not being parsed as a string but as a variable. It doesn't appear to be an Issue with Middleman or Gulp Starter.

I can get the url to transform just fine 
![image](https://cloud.githubusercontent.com/assets/725067/14331799/be6ec504-fc3e-11e5-86dc-3bcad47a045f.png)

**Comment by joshukraine** [comment] 2016-04-07 05:42
After further troubleshooting, I think the issue is related specifically to jQuery and/or Moment (and possibly other such libraries?) being combined with the `asset_host` config. In essence, if `asset_host` is activated in `config.rb` _and_ jQuery is required, the resulting javascript bundle is invalid.

I've tried this in two different projects and I can consistently reproduce the issue in both places. One is my fork of your repo (https://github.com/joshukraine/middleman-gulp-starter) and the other is one of my own that uses Browserify instead of Webpack: https://github.com/joshukraine/mm4-example

Any suggestions? Maybe I'm missing something? Thanks.

**Comment by craigmdennis** [comment] 2016-04-07 09:59
I'd suggest putting together a reduced test case so people don't have to dig through everything in your repo. The smallest possible amount of code to reproduce the error will help in identifying the cause. I can't replicate any of the issues you're describing.

**Comment by joshukraine** [comment] 2016-04-07 10:36
Sure, I'd be happy to do that. But I'm not sure what more I could remove that would simplify the relevant code. The first of the two repos I've mentioned above is merely a clone of yours with jQuery added. The second is essentially a stock Middleman 4 app, also with jQuery added and few css extras.

I'm sorry this has drug out. It's not my intention to be a nuisance - I'd just like to get MM4 working with Gulp, and I appreciate your time.

One last question: am I correct in my understanding that on your machine, if you add jQuery to your gulp starter project as I have done (or just [clone my fork](https://github.com/joshukraine/middleman-gulp-starter) of it), and run `middleman build`, the bundled javascript correctly embeds the asset host URL? No syntax errors? Would it be possible to have a gist of the output from your end?

Thanks again.

**Comment by craigmdennis** [comment] 2016-04-07 11:22
Ok I've managed to replicate it. I'm unsure as to why the asset host is being added into javascript file though.

It seems to change `e.deprecate=function(){},e.paths=[],e.children=[]` into `e.deprecate=function(){},//joshukraine-middlemantest.s3-website-eu-west-1.amazonaws.com/javascripts/e.paths=[],e.children=[]` for no apparent reason.

**Comment by joshukraine** [comment] 2016-04-07 20:52
FYI, I believe I've discovered the reason MM is inserting the asset URLs into the javascript. It's a regex issue in Middleman. Good news is that there's apparently a workaround. Details here: https://github.com/middleman/middleman/issues/1873#issuecomment-207080980

Thanks again for all your help. Sorry for the trouble. Great job with middleman-gulp-starter. Really looking forward to using it. :)
